[project]
name = "my-dropbox-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=23.1.0",
    "boto3>=1.36.16",
    "requests>=2.32.3",
    "typer>=0.15.1",
    "types-boto3[essential]>=1.36.16",
]